FROM ubuntu:16.04
# Install packages.
RUN apt-get update
RUN apt-get install -y python3 python3-dev python3-pip
RUN apt-get install -y libjpeg-dev libopencv-dev python-opencv
RUN apt-get install -y python3-pyqt5
RUN apt-get install -y cython
#RUN apt-get install -y pyfai==0.15.0
RUN apt-get install -y gfortran
RUN apt-get install -y mesa-common-dev
RUN pip3 install --upgrade pip
RUN pip3 install pyFAI==0.15.0

#RUN pip3 install --upgrade scikit-image
#RUN pip3 install --upgrade tifffile
RUN pip3 install --upgrade numpy
RUN pip3 install --upgrade lmfit
RUN pip3 install --upgrade pandas
#RUN pip3 install --upgrade scikit-learn
#RUN pip3 install --upgrade ConfigParser
RUN pip3 install --upgrade pillow
RUN pip3 install --upgrade matplotlib
#RUN pip3 install --upgrade fabio
RUN pip3 install --upgrade Cython
#RUN pip3 install --upgrade peakutils
#RUN pip3 install --upgrade h5py
#RUN pip3 install --upgrade scipy
#RUN pip3 install --upgrade matplotlib
#RUN pip3 install --upgrade musclexflibs
#RUN pip3 install --upgrade PyMca5

RUN pip3 install --upgrade musclex

ARG USER_ID
ARG GROUP_ID
RUN addgroup --gid $GROUP_ID user
RUN adduser --disabled-password --gecos '' --uid $USER_ID --gid $GROUP_ID user
USER user

#ADD musclex /musclex/musclex
#
#ADD LICENSE.txt /musclex/LICENSE.txt
#ADD MANIFEST /musclex/MANIFEST
#ADD README.md /musclex/README.md
#ADD setup.cfg /musclex/setup.cfg
#ADD setup.py /musclex/setup.py
#ENV TMP_PATH $PYTHONPATH
#ENV PYTHONPATH /musclex/:$TMP_PATH
#WORKDIR /musclex/
#RUN python /musclex/setup.py install
#
